### ISSUE TITLE
Issues with Page TSconfig

### ISSUE THREAD

**Issue by SventB** [tomasnorre/crawler#1000]
**Current Behavior**
I'm not able to move my configuration from configuration records to Page TSconfig.

**Expected behavior/output**
Configuration is possible in Page TSconfig, like it is possible with configuration records.

**Steps to reproduce**
I'm having this record (all fields not visible here aren't modified):
![crawler](https://user-images.githubusercontent.com/2690489/209966185-bc55bbe8-5f11-4ade-bd16-c59aa8a52426.PNG)
I'm transferring this in Page TSconfig:
```
tx_crawler.crawlerCfg.paramSets.pages_content_root1 = &what-to-do-here=unknown
tx_crawler.crawlerCfg.paramSets.pages_content_root1 {
    procInstrFilter = tx_indexedsearch_reindex
    force_ssl = 0
}
```
1) Why to I have to set a GET parameter (see "&what-to-do-here=unknown")? In my record I also didn't set one.
2) Configuration option "force_ssl=0" results in an error:
`AOE\Crawler\Service\UrlService::getUrlFromPageAndQueryParameters(): Argument #4 ($httpsOrHttp) must be of type int, string given, called in \typo3conf\ext\crawler\Classes\Controller\CrawlerController.php on line 323`
3) Configuration option "force_ssl" isn't described in documentation (https://docs.typo3.org/p/tomasnorre/crawler/main/en-us/Configuration/PageTsconfigReference%28txCrawlercrawlercfg%29/Index.html)

**Environment**
- Crawler version(s): 11.0.7
- TYPO3 version(s): 11.5.21
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Off topic**
Congratulations for the 1000th issue ;-) 
And thank you for EXT:crawler <3

**Comment by tomasnorre** [comment]
Thanks for your report and support. I'll look into this.

**Comment by SventB** [comment]
Please do not close :)

**Comment by SventB** [comment]
And once again: Please do not close :)
