### ISSUE TITLE
Exception: No Content Object definition found at TypoScript object path "tt_content.list.20.9"

### ISSUE THREAD

**Issue by cstrizzolo** [tomasnorre/crawler#1006]
I get the attached error in my log file when the crawler runs through a cron job:

15 21 * * * /usr/bin/php (...)/typo3/sysext/core/bin/typo3 crawler:buildqueue 2867 mysite --depth 99 --mode exec

I don't know if it is just a problem related to my own installation or if it might be a general issue.

Any hints?
Any suggestions about how I could investigate further?

**Environment**
- Crawler version(s): 11.0.7
- TYPO3 version(s): 11.5.24
- PHP version: 8.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Additional context**
[error.txt](https://github.com/tomasnorre/crawler/files/10804795/error.txt)

**Comment by tomasnorre** [comment]
Sorry, for the late response @cstrizzolo.

This looks like a problem with the TS template and not the crawler.
I'll close this issue, please reopen if I'm mistaken, but please provide more information if reopening the issue.
