### ISSUE TITLE
[FEATURE] TYPO3 v12 compability

### ISSUE THREAD

**Issue by linawolf** [tomasnorre/crawler#1020]
### Is your feature request related to a problem? Please describe

I would like to use the crawler with TYPO3 v12

### Describe alternatives you've considered

What can I do to help?

**Comment by tomasnorre** [comment]
I would love to see that too. The main branch is close to be done, but as I have been online since February it's not really moving forward at the moment.

**Comment by nhovratov** [comment]
@tomasnorre Can I help you in any way? Do you know what is missing for complete compatibility?

**Comment by tomasnorre** [comment]
@nhovratov To be honest, I have lost the overview, but issue #823 should give some ideas. As am currently not working, I don't really know it from my top of my head anymore, and not in a good state to look into it. 

Thank both to you and @linawolf for offering your help, but not really able to enable you to help me much right now, unless you see issues with 12 compat yourself. 

The main branch is close to done, but don't know how much is missing. 

The main branch is ment for v12 compat only, so we can do no harm for older versions and they have a different release.

**Comment by IndyIndyIndy** [comment]
Current state of update for TYPO3 v12.4:
https://github.com/tomasnorre/crawler/compare/main...IndyIndyIndy:crawler:main

Everything from backend module to scheduler tasks appears to run now in my local setup...

Still missing: 
- Replace the deprecated TypoScriptParser call with the new Typoscript parser.
- Adjust and run all tests

Will look into that tomorrow.

**Comment by IndyIndyIndy** [comment]
Okay:
- Unit Tests are working now, 

But I currently can't get the functional (or acceptance) tests to run, because the mysql driver returns "Connection refused". 
Seems like some setup step is missing. 
I do not know how this testing-framework particularly is working, I usually do testing setups via docker container configs, as described in https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Testing/ExtensionTesting.html.
I do not have the time currently to rewrite the whole testing setup (or find out what is currently wrong with this setup)

Maybe someone else is more well-versed in this setup...

**Comment by tomasnorre** [comment]
Thanks for your contribution. I hope someone will pick it up, will not get merged before tests are green. Unfortunately I cannot do it myself atm.

**Comment by DavidBruchmann** [comment]
looks to me like it would be pragmatic to transfer the ownership of this repository to [friendsOfTypo3](https://github.com/FriendsOfTYPO3/extension_builder/)

**Comment by tomasnorre** [comment]
I could be an option. But if people from FriendsOfTypo3 are willing to contribute there, why not here? Given contributor's rights isn't a problem.

**Comment by DavidBruchmann** [comment]
> Given contributor's rights isn't a problem.

It was my impression that you've very limited time to care about anything currently, even about nearly ready PRs, and also it might a problem for you to be even online.  
It wasn't meant in any kind offensive, I don't know your reasons or situation, so excuse if my impression was somehow wrong.
I think the work and input of @IndyIndyIndy might be quite useful, so perhaps there is no need to do much more.
I just read the issue, but never use the crawler at all by myself, so I've no personal preference how to deal with anything here, it was just a thought ;-)

**Comment by tomasnorre** [comment]
I didn't see it offensive. The work from @IndyIndyIndy is merged in the main branch. Without his work, it would be further away from a v12 release.

I will not comment on my situation in public, but feel free to reach out on other media if you want. 

I'll consider it. I have asked for support in the TYPO3 Crawler channel, without any luck.

**Comment by tomasnorre** [comment]
I'll close this issue as there is a v12 compatible release.
