### ISSUE TITLE
PHP Warning: Undefined array key "set_id" and Undefined array key "qid"

### ISSUE THREAD

**Issue by zenoussi** [tomasnorre/crawler#1021]
Hi!
My log fills up with about 200 outputs of these messages per scheduler task:
Core: Error handler (BE): PHP Warning: Undefined array key "set_id" in /typo3cms/xxx/releases/8/public/typo3conf/ext/crawler/Classes/Middleware/FrontendUserAuthenticator.php line 119
Core: Error handler (BE): PHP Warning: Undefined array key "qid" in /typo3cms/xxx/releases/8/public/typo3conf/ext/crawler/Classes/Middleware/FrontendUserAuthenticator.php line 119

However, the indexing itself seems to work.
Any ideas?

Thanks a lot
Ulli

**Environment**
- Crawler version: 11.0.7
- TYPO3 version: 11.5.30
- PHP 8.1.21
- Composer Mode: yes

**Additional context**
Using `indexed_search`

**Comment by tomasnorre** [comment]
Sorry for the late action. As there are already some dialog going on in #1031, I'll close this one as a duplicate. It isn't meant to be rude, but I have overlooked this issue. I'm sorry for that.
