### ISSUE TITLE
[DOC] Documentation missing about _cli_-user needing admin-rights

### ISSUE THREAD

**Issue by metapublic-gbr** [tomasnorre/crawler#1024]
Typo3 11.5.33
Crawler 11.0.7

My observations are: 

calling `crawler:buildQueue` in all variations only works if be-user _cli_ has field "admin" enabled.

If this can be confirmed, I would suggest to add a new page "installation" to the documentation and put this information there.

**Comment by tomasnorre** [comment]
As this is information is already on the page that I linked to, I will close this issue. 
https://github.com/tomasnorre/crawler/blob/main/Documentation/ExecutingTheQueue/ExecutingQueueWithCron-job/Index.rst?plain=1#L29
