### ISSUE TITLE
File missing autoload.php

### ISSUE THREAD

**Issue by Medesis** [tomasnorre/crawler#1070]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.
The file require \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('crawler') . /Resources/Private/Php/Libraries/vendor/autoload.php is missing.

**Environment**
- Crawler version(s): [12.0.0-dev]
- TYPO3 version(s): [12.4.15]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]

**Comment by tomasnorre** [comment]
My bad, I know where the problems is. 

I'll make sure that I create a new release on of the following days.

**Comment by tomasnorre** [comment]
Fixed in https://github.com/tomasnorre/crawler/releases/tag/12.0.3

**Comment by Medesis** [comment]
Hey,
i get the same error:
PHP Warning: require(/var/www/html/typo3conf/ext/crawler//Resources/Private/Php/Libraries/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/typo3conf/ext/crawler/ext_localconf.php line 7

Is there anything I need to bear in mind during installation?

**Comment by tomasnorre** [comment]
@Medesis, Still after updating to 12.0.3? Or 11.0.9?

**Comment by Medesis** [comment]
After update from 12.0.0 to 12.0.3

**Comment by tomasnorre** [comment]
@Medesis Strange. If I download the release file manually from https://extensions.typo3.org/extension/crawler and unzip it. The file is there. Can you please check manually if  you file is there from the download Resources/Private/Php/Libraries/vendor/autoload.php and where did you download from ? 

extensions.typo3.org or github-release? The github release doesn't contain it, that's true, as it's a github-release not a extension release, they don't have the logic behind it with running composer etc. it simply compresses the repository for that tag.

**Comment by Medesis** [comment]
> Fixed in https://github.com/tomasnorre/crawler/releases/tag/12.0.3
I have download its there: https://github.com/tomasnorre/crawler/releases/tag/12.0.3
Now in: https://extensions.typo3.org/extension/crawler i see the file.
Thx

**Comment by tomasnorre** [comment]
Thanks. 

GitHub Releases unfortunately, doesn't contain what's needed for non-composer projects.
