### ISSUE TITLE
Process Queue throws Truncated incorrect DECIMAL value

### ISSUE THREAD

**Issue by xyng** [tomasnorre/crawler#1082]
## Bug Report

**Current Behavior**
Running the command `crawler:processQueue` ends with exception: `Truncated incorrect DECIMAL value: 'VALUE_HERE'`

**Expected behavior/output**
Running the command does not throw exception.

**Steps to reproduce**
Run command `crawler:processQueue`.

**Environment**
- Crawler version(s): master, 12.0.3
- TYPO3 version(s): 12.4.16
- PHP version(s): 8.3
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
https://github.com/tomasnorre/crawler/blob/68e72580ad300ab8ac545daf64c62f62cc897871/Classes/Domain/Repository/QueueRepository.php#L330
Use `ArrayParameterType::STRING`.
The field `process_id` is defined as `varchar`:
https://github.com/tomasnorre/crawler/blob/1606131d50a7bc6e0676f8a30a92f6b52f5de605/ext_tables.sql#L15
https://github.com/tomasnorre/crawler/blob/68e72580ad300ab8ac545daf64c62f62cc897871/ext_tables.sql#L34

I can send a PR, but since this is probably a one-line change, it may be more time-consuming for you.
Please tell me if you want me to make one.

**Additional context**
-

**Comment by tomasnorre** [comment]
Thank you for your report. Do you get this exception every time running the command? 
I have never paid attention to it.

If you make a PR I would be happy to merge it after evaluating it. I cannot say from the top of my head if the solution is the correct one, would need to dig a bit, but sounds correct from reading it. But would need to look at possible side effects.

Best case would be if you can add a test that proves that the exception happens and disappears after the fix.

**Comment by xyng** [comment]
Hi @tomasnorre - thanks for your reply.

I started to see this error every few minutes from our scheduler and decided to investigate.
I then found this type mismatch. Since the `process_id` is stored as a varchar and the contents seem to be md5-values, and integer will fail to be converted.

I will prepare a PR and also try to create a test.

**Comment by tomasnorre** [comment]
Resolved by https://github.com/tomasnorre/crawler/pull/1083
