### ISSUE TITLE
Unwanted PHP warning for failed unserialize

### ISSUE THREAD

**Issue by ulrichmathes** [tomasnorre/crawler#1090]
## Bug Report

**Current Behavior**
`JsonCompatibilityConverter:53` rises PHP warning

**Expected behavior/output**
When JsonCompatibilityConverter tries to unserialize a string and fails, there should be no warning.
There is a `try catch` block, but unserialize emits a warning instead of throwing an exception.

**Steps to reproduce**
I think JsonCompatibilityConverterTest will rise this warning but unitTests are configured as `failOnWarning="false"`.

**Environment**

- Crawler version(s): 12.0.4
- TYPO3 version(s): 12.4
- **PHP version(s): 8.3**
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
suppress the warning via `@unserialize` instead of not applying `try catch`?

**Additional context**
This issue is caused by the change in PHP 8.3:
> 8.3.0	Now emits [E_WARNING](https://www.php.net/manual/en/errorfunc.constants.php#constant.e-warning) when the passed string is not unserializeable; previously [E_NOTICE](https://www.php.net/manual/en/errorfunc.constants.php#constant.e-notice) was emitted.

**Comment by tomasnorre** [comment]
This looks like it could be related to #1087, do you agree?

**Comment by ulrichmathes** [comment]
Same root but in my case both commands `crawler:buildQueue` and `crawler:processQueue` proceed running while generating a lot of warnings.

**Comment by ulrichmathes** [comment]
But yes, we could close this issue as its not really relevant if the command is running but rising warnings or gets terminated after the first warning.

**Comment by tomasnorre** [comment]
I'll close this issue as @ulrichmathes suggested.
