### ISSUE TITLE
Dev version for Typo3 13.4.x

### ISSUE THREAD

**Issue by gmt-it** [tomasnorre/crawler#1114]
Hello,

I'm new to Typo3 and have been working with Typo 13 since August. I'm slowly getting a better overview... I'm currently looking into indexed search and tx_news. Is the crawler already available in a dev version for typo3 13.4.x? I'd like to try it out and test it.

TIA

Guido

**Comment by tomasnorre** [comment]
Hi, 

There is no official release of the TYPO3 Crawler compatible with TYPO3 13 LTS, but working on it. 

The work-in-progress can be found in this branch. https://github.com/tomasnorre/crawler/tree/ci/test-with-typo3-v13

Technically all should work, but I'm not done writing the tests proving that I'm done :)

**Comment by gmt-it** [comment]
Thanks Tomas.

I will install and test it.

Best regards

Guido

**Comment by tomasnorre** [comment]
There is a TYPO3 Crawler channel on the TYPO3 Slack, if you have any questions etc, you can ask there.  https://typo3.org/community/meet/chat-slack

I'll close this issue.
