### ISSUE TITLE
Display error message in buildQueue command

### ISSUE THREAD

**Issue by brotkrueml** [tomasnorre/crawler#615]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When starting the buildQueue command with a configuration which doesn't work (e.g. a page veto for that specific page is set) the following result is shown: ``Putting 0 entries in queue``. There is not hint, why they are no entries put into the queue where they should some. See also https://github.com/AOEpeople/crawler/issues/516#issuecomment-669759086

**Describe the solution you would like**
The command calls CrawlerController->getPageTreeAndUrls() which returns a "code" (which is HTML). In that code there is probably an error message which should be shown. By now, the command ignores that code. In the described case the codes holds the reason: the page is veto'd, so there are 0 entries in queue.

This would make the configuration error obvious, for now you have to debug to see the error message. I don't know, why it's HTML there (perhaps it's shown in the module?). So the code must be trimmed and striptags'd before output.

**Comment by tomasnorre** [comment]
I'm thinking about how this could be changed. Outputting the HTML doesn't look good in the cli even with strip_tags.
And I'm not sure it gives enough information either. 

I'm considering if the `getPageTreeAndUrls()` and  `drawURLs_addRowsForPage()` should return an object of some type instead.
This would have two advantages:

1. Have HTML and logic separated
2. Having the possibility to format the result fitted for the cli

What do you think about that @brotkrueml ? 

![Screenshot from 2020-08-06 21:57:17](https://user-images.githubusercontent.com/1212481/89576626-d2356a80-d82f-11ea-8975-c2b061ae1487.png)

**Comment by brotkrueml** [comment]
Yes, a small object is pretty. With a renderText() and a renderHtml() method perhaps. And both use a Standalone Fluid template, so the view is separated from the PHP code.

**Comment by tomasnorre** [comment]
Thanks for your input, will let you know when I have a review ready, will not be this weekend though ;)

**Comment by brotkrueml** [comment]
That's fine for me, no hurry.

**Comment by tomasnorre** [comment]
I have a small prove of concept already, would need to check the tests, side effects etc. before I can give you something to review and test, but looks like it works how I imagined it.

**Comment by tomasnorre** [comment]
Doh, I have deleted my branch, so would need to do this again..
