### ISSUE TITLE
Crawler builds queue on 10.4 project, but can't process it - composer install

### ISSUE THREAD

**Issue by mediaconform** [tomasnorre/crawler#760]
## Bug Report

**Current Behavior**
Crawling queues are built, but not properly processed.

**Expected behavior/output**
No errors while processing the queue and status 'ok' for successfully processed pages in crawler log.

**Steps to reproduce**

***A. Command Line Interface***
When I do

`$: vendor/bin/typo3 crawler:buildQueue 1 default --depth 4 --mode exec`

Crawler builds a queue with all URLs without errors. After that Crawler starts processing every single URL returning an error for each URL like this

```
https://some.domain.name/and/slug-one () =>
Error checking Crawler Result: ...

https://some.domain.name/and/slug-two () =>
Error checking Crawler Result: ...

https://some.domain.name/and/slug-three () =>
Error checking Crawler Result: ...
```

***B. TYPO3 Backend***
I create a queue via 'Info > Site Crawler > Start Crawling', choosing the configuration, depth and schedule, finally clicking 'Crawl URLs' button.

'Info > Site Crawler > Crawler log' then shows the list of pages, but the 'Status' column contains only '-' for each page. 

When I 'Add process' in backend 'Info > Site Crawler > Crawling Processes' the process is added to the 'Process States' list, but as soon as I click on 'Refresh' to show the progress, the newly added process is imediatly gone. Clicking on 'Show finished and terminated processes' reveals a red dot in the 'State' column and 'Process was cancelled' in the 'Progress' column for that particular process.

**Environment**
- Crawler version: 9.2.5
- TYPO3 version: 10.4.17
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
n/a

**Additional context**
I am usind indexed_search v. 10.4.17

**Comment by tomasnorre** [comment]
hi @mediaconform, 
Can you please share how your crawler configuration looks like?

**Comment by mediaconform** [comment]
Crawler configuration according to LocalConiguration.php:

```
        'crawler' => [
            'cleanUpOldQueueEntries' => '1',
            'cleanUpProcessedAge' => '2',
            'cleanUpScheduledAge' => '7',
            'countInARun' => '100',
            'crawlHiddenPages' => '0',
            'enableTimeslot' => '1',
            'frontendBasePath' => '/',
            'makeDirectRequests' => '1',
            'maxCompileUrls' => '10000',
            'phpBinary' => 'php',
            'phpPath' => '',
            'processDebug' => '1',
            'processLimit' => '1',
            'processMaxRunTime' => '300',
            'processVerbose' => '1',
            'purgeQueueDays' => '14',
            'sleepAfterFinish' => '10',
            'sleepTime' => '1000',
        ],

```

**Comment by mediaconform** [comment]
Crawler settings

![TYPO3 - Crawler Settings](https://user-images.githubusercontent.com/7619933/125754979-ef9fb02a-3151-431e-aa99-7638385277d1.png)

**Comment by tomasnorre** [comment]
Thanks for the input. I was referring to the Crawler-Configuration Record. 
https://docs.typo3.org/p/aoepeople/crawler/9.2/en-us/Configuration/ConfigurationRecords/Index.html

**Comment by mediaconform** [comment]
I updated the comment above with a screenshot of my crawler configuration done in the backend. - I don't use any typoscript regarding the crawler configuration

**Comment by tomasnorre** [comment]
As both Crawler 9.x.y and 10.x.y are compatible with TYPO3 10, would you mind trying to update the crawler to see if the issue persists?

**Comment by tomasnorre** [comment]
This sounds a little similar to https://github.com/tomasnorre/crawler/issues/757, what do you think?

**Comment by mediaconform** [comment]
Hi @tomasnorre , sorry for the late reply.
I've updated the crawler and in the TYPO3 backend at first sight it seems to work fine, but having a closer look it turns out, that all the results of the crawled pages are still not saved. So in the end the problem is the same as it has been before.

And yes it looks similar to #757 - thanks for digging into this issue.

**Comment by tomasnorre** [comment]
No worries, every feedback is appreciated, regardless of when. I'll close this and mark as duplicate for now.

**Comment by tomasnorre** [comment]
Closed.

Marked as duplicate: #757
