### ISSUE TITLE
Crawler Process status : 503 Service Unavailable

### ISSUE THREAD

**Issue by qctypo** [tomasnorre/crawler#770]
## Bug Report

**Current Behavior**
I have installed plugin and trying to index pages by crawler process manually.
I am using crawler 9.2.6 on TYPO3 9.5.28 non composer mode.
When I add Process it always show me status : 503 service Unavailable  and page is not indexed
Could you please help me to sort this.
While adding configuration  in baseurl field is empty. (Also try with adding baseurl)

**Expected behavior/output**
Status should be OK and page should be indexed.

**Steps to reproduce**
- Start Crawling ->select Configuration->Crawl URLs 
- Continue and show log
- Add Process Queue

**Environment**
- OS : Linux 5.4.0-44-generic
- Php : 7.3.25
- CLI path : /usr/local/bin/php /home/www/XXX/html/typo3/typo3/sysext/core/bin/typo3 crawler:processQueue
- TYPO3 9.5.28
- Crawler 9.2.6 
- no Composer mode
- Page has no htaccess password protection added.

**Additional context**
For FE search I am using Indexed Search plugin.

![image](https://user-images.githubusercontent.com/88437191/128178623-8b3c66e8-a73a-4405-afb2-7af2802c8552.png)

**Comment by tomasnorre** [comment]
Does the "Error: 503" say more when you hover over the text?

**Comment by qctypo** [comment]
> Does the "Error: 503" say more when you hover over the text?

No :(

**Comment by tomasnorre** [comment]
And the frontend is working like expected?
A 503 is a server error, so do you have any information from sys_log or apache/php log? 

Do you have the crawler settings at directRequest active or not? 
https://docs.typo3.org/p/aoepeople/crawler/master/en-us/Configuration/ExtensionManagerConfiguration/Index.html#extension-manager-configuration

**Comment by qctypo** [comment]
@tomasnorre 
I could not find any error log related to this in sys_log.
This is  on mittwald server.

And right now  crawler settings at directRequest is not active.
Even I tried to  make it active but in that case nothing happened  not even 503 error in status or ok shows. No process happen if i make it active.

Also regarding to your question frontend is working --> then yes there is no issue with FE , it is working fine as it is.

**Comment by tomasnorre** [comment]
Thanks for the update. I'll look into this. 

Please update the issue if you find any additional information.

**Comment by tomasnorre** [comment]
Could it be related to? 
https://github.com/AOEpeople/crawler/issues/758

That's also on a mittwald server.

**Comment by qctypo** [comment]
I don' t think it is related to that because cleanup process is working fine.

**Comment by tomasnorre** [comment]
ok. Thanks for the info.

**Comment by tomasnorre** [comment]
As both Crawler 9.x.y and 10.x.y are compatible with TYPO3 9, would you mind trying to update the crawler to see if the issue persists?

**Comment by tomasnorre** [comment]
Can this be related to #851 where the issue is the "baseURL" not been taking from the Sites configuration?
