### ISSUE TITLE
?MP= is added when building the queue

### ISSUE THREAD

**Issue by brotkrueml** [tomasnorre/crawler#781]
## Bug Report

**Current Behavior**
When running the crawler:buildQueue command an empty MP query parameter is added to the URLs:

```
ddev typo3 crawler:buildQueue 3 deployment --mode exec
Executing 4 requests right away:
[21.09.21 09:16] https://website.ddev.site/en/?MP=
[21.09.21 09:16] https://website.ddev.site/de/?MP=
[21.09.21 09:16] https://website.ddev.site/pl/?MP=
[21.09.21 09:16] https://website.ddev.site/tr/?MP=
```

**Expected behavior/output**
The MP query parameter is omitted when not necessary.

**Steps to reproduce**
Call crawler:buildQueue on cli.

**Environment**
- Crawler version: 10.0.2
- TYPO3 version: 10.4.20
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Comment by tomasnorre** [comment]
I haven't looked into this yet, but this must be a bug introduced somewhere between 9.x and 10.x will look into this after my vacation. PRs are welcome if you get any further ;)

**Comment by brotkrueml** [comment]
Yes, that's it. Will provide a PR for this as you guided me successfully to the code ;-)
