### ISSUE TITLE
[FEATURE] Add description for the crawler tasks inside CLI

### ISSUE THREAD

**Issue by PhilippKuhlmay** [tomasnorre/crawler#783]
### Is your feature request related to a problem? Please describe

When I use the CLI command 'ddev typo3' or 'vendor/bin/typo3' I get the list of all available commands with descriptions.
The EXT:crawler doesn't provide these descriptions.

It would be nice to add descriptions to the 3 avaiable crawler tasks.

<img width="720" alt="Bildschirmfoto 2021-09-23 um 14 56 16" src="https://user-images.githubusercontent.com/57705869/134510567-b9e01a56-24cf-4a98-b27a-437de1e2675e.png">

### Describe the solution you would like

Add descriptions for all CLI commands

Something like this:
<img width="499" alt="Bildschirmfoto 2021-09-23 um 13 55 46" src="https://user-images.githubusercontent.com/57705869/134510613-92a5e7ee-3164-4599-8ffb-4a4a0c26a5b0.png">

### Describe alternatives you've considered

No alternative

**Comment by tomasnorre** [comment]
Thanks for your suggestion. I will look into this, but as this is a ddev only feature, it will not have my highest priority, but it could be fairly simple to resolve.

**Comment by tomasnorre** [comment]
I cannot reproduce this. 
Which TYPO3 version are you on? 

![Screenshot 2021-09-28 at 14 58 51](https://user-images.githubusercontent.com/1212481/135091575-eb417665-2c1a-4f8f-8ce6-1fa9f6ecf0b3.png)

**Comment by PhilippKuhlmay** [comment]
TYPO3 11.4. I see that the description exists in 10.4. 
Maybe it is because the configuration for the CLI tasks and its description moved into Configuration/Services.yaml in TYPO3 11?
