### ISSUE TITLE
Placeholder for follow up improvements for issue #754

### ISSUE THREAD

**Issue by tomasnorre** [tomasnorre/crawler#816]
From @brotkrueml comments in review: 
https://github.com/tomasnorre/crawler/pull/754#issuecomment-864586872

I have extracted the comments into separate issues, to ease the fixes and keep the PRs smaller.

- https://github.com/tomasnorre/crawler/issues/1096
- https://github.com/tomasnorre/crawler/issues/1097
- https://github.com/tomasnorre/crawler/issues/1099
- https://github.com/tomasnorre/crawler/issues/1100

----

Now a URL with MP is used:

    Processing
    https://website.ddev.site:8443/en/?MP= () => 
    OK: 

This shouldn't be an issue, as the correct canonical is used (without MP), just a little bit unaesthetic.

Cannot reproduce this anymore. @tomasnorre 

----

Running the command without `depth`:

    ddev t3cmd crawler:buildQueue 3 deployment --mode exec                                                                                                                                
    
    Executing 4 requests right away:
    [20.06.21 17:19] https://website.ddev.site:8443/en/?MP= (URL already existed)<br>[20.06.21 17:19] https://website.ddev.site:8443/de/?MP= (URL already existed)<br>[20.06.21 17:19] https://website.ddev.site:8443/pl/?MP= (URL already existed)<br>[20.06.21 17:19] https://website.ddev.site:8443/tr/?MP= (URL already existed)

omits the detailled information from above for other pages. The `<br>` tag should be converted to a new line on console.

Edit: I cannot reproduce this as of `crawler 12.4.0` @tomasnorre 

----

I am getting many empty lines when calling a `buildQueue` command with `depth`. Perhaps these empty lines come from "successful" pages without any output. I think, they should be avoided.

Edit: Fixed as part of #1097 @tomasnorre

**Comment by tomasnorre** [comment]
> Now a URL with MP is used:
> 
> ```
> Processing
> https://website.ddev.site:8443/en/?MP= () => 
> OK: 
> ```
> 
> This shouldn't be an issue, as the correct canonical is used (without MP), just a little bit unaesthetic.

@brotkrueml I know it's a long time ago, but do you recall how to reproduce this? I cannot get it reproduced.

**Comment by brotkrueml** [comment]
Sorry, no. But if you can't reproduce it, maybe that is gone? :-)

**Comment by tomasnorre** [comment]
Thanks for your feedback, didn't expect that to be honest either. I'll see if I cannot reproduce it in near future, I'll expect it to be solved until it gets reported again.

**Comment by tomasnorre** [comment]
I'll close this issue for now, as all issues, that still needs to be address is addressed in a new issue.
