### ISSUE TITLE
Reminders for 12.0.0 - Release

### ISSUE THREAD

**Issue by tomasnorre** [tomasnorre/crawler#823]
- [x] #903
- [x] Remove `modMenu()` in `BackendModule`
- [x] #911
- [x] #914
- [x] #905
- [x] #918
- [x] Switch to Denpendency Inject see https://github.com/tomasnorre/crawler/pull/835#discussion_r739769581
- [x] #920
- [x] #906
- [x] #908
- [x] #856
- [x] #916
- [x] Add more TypeHints
- [x] PHP 7.4 TypeHints 
- [x] #895
- [x] #896 
- [x] #969
- [x] #970
- [x] #992 
- [x] #1034 
- [x] #1040

**Comment by danir-de** [comment]
Do you have an idea, when this might be finished? v12 is already matured and v13 is already on its way.

**Comment by tomasnorre** [comment]
I cannot work on this myself for now, so I don't know. I depend on help from the outside. 
https://twitter.com/tomasnorre/status/1729056842398195966

**Comment by tomasnorre** [comment]
Just released as TYPO3 12 Compatible version of the Crawler. 
https://github.com/tomasnorre/crawler/releases/tag/12.0.0
