### ISSUE TITLE
Frontend plugins doesn't work when crawler is installed

### ISSUE THREAD

**Issue by brotkrueml** [tomasnorre/crawler#830]
## Bug Report

**Current Behavior**
Using crawler on a TYPO3 v11 installation throws the following exception in frontend:

    The default controller for extension "News" and plugin "Pi1" can not be determined. Please check for TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php.

After deinstalling the news extension the next plugin displays a similar error.

After deinstallation of crawler everything works fine.

The error comes from initializing the concrete ConfigurationManager where `$GLOBALS['TYPO3_REQUEST'] is null and hence the BackendConfigurationManager is instantiated wrongly for frontend.

See: https://github.com/TYPO3/typo3/blob/master/typo3/sysext/extbase/Classes/Configuration/ConfigurationManager.php#L49

**Expected behavior/output**
Plugin displayed correctly.

**Steps to reproduce**
Install news and crawler on a TYPO3 v11.5 installation and display e.g. the news list view.

**Environment**
- Crawler versions: 10.0.3, 11.0.0
- TYPO3 version(s): 11.5.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Possible Solution**

I tracked it down to the FrontendUserAuthenticator middleware. After commenting out the initialisation of the `QueueRepository` in the constructor everything works as expected. I assume, that it is perhaps too early now to instantiate a repository. Perhaps the instantiation of the repository triggers the creation of the `ConfigurationManager`, but the request object is not available yet.

Changing the position of the middleware solves this issue, but I don't know, if the logic of the middleware works correctly now:

    'frontend' => [
        'aoe/crawler/authentication' => [
            'target' => FrontendUserAuthenticator::class,
            'after' => [
                'typo3/cms-frontend/static-route-resolver',
            ],
        ],
    ],

Strangely, when I add the `before` part (`typo3/cms-frontend/page-resolver`) the error occurs again.

Another solution may be to use the `QueryBuilder` instead of the repository.

**Comment by tomasnorre** [comment]
This is resolved with https://github.com/tomasnorre/crawler/commit/d01a00709de846873cae14b0290e1ceac2abfbf4
