### ISSUE TITLE
Support StaticFileCache and do not destroy the middleware stack

### ISSUE THREAD

**Issue by lochmueller** [tomasnorre/crawler#837]
## Bug Report

**Current Behavior**
The current problem is, that EXT:crawler destroy the middleware stack, by calling the handler and ignore the response in the middleware:
https://github.com/tomasnorre/crawler/blob/main/Classes/Middleware/CrawlerInitialization.php#L69
So StaticFileCache but also other middlewares in the middleware stack got an useless response object.

The reason for that is, because there are some serialized meta information in the Response, that are use by the crawler itself:
https://github.com/tomasnorre/crawler/blob/main/Classes/Middleware/CrawlerInitialization.php#L80

**Expected behavior/output**
A valid response object that is generated by the middleware stack and not a fresh response object.

**Steps to reproduce**
Using EXT:crawler and EXT:staticfilecache (without the "NoCrawler" rule, because that currently check if the request is a crawler request and do not cache then)

**Environment**
- Crawler version(s): dev-master
- TYPO3 version(s): 10 & 11
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
Write the crawler meta information in some kind of header like "X-Crawler" of the original response object. So the middleware stack is not compromised be the crawler middleware. You can evaluate the Header instead of the content in the the crawling strategy: https://github.com/tomasnorre/crawler/blob/main/Classes/CrawlStrategy/GuzzleExecutionStrategy.php#L54

Then StaticFileCache get a response object with the right content and I can drop the "Disable Static File Cache with Crawler calls"-rule in EXT:staticfilecache.

Any addional ideas?!

Regards,
Tim

**Comment by tomasnorre** [comment]
I have tried to setup staticfilecache together with the crawler, but I don't find where this config "noCrawler" can be set. I don't find anything in the documentation. Can you please point me to this @lochmueller ?

**Comment by lochmueller** [comment]
Hey @tomasnorre 
you could comment out this lines:
https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/Rule/NoCrawlerCall.php#L21
https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/Rule/NoCrawlerCall.php#L22

Then the cache rule do not disable the cache on crawler calls.
There is no configuration option, because it don't work with the EXT:crawler currently.

If you disable the rule, SFC will cache your serialized meta data information in the StaticFileCache. If the middleware return the real content as described in this issue here, the HTML content should be cached.

Regards,
Tim
