### ISSUE TITLE
Crawler don´t start -

### ISSUE THREAD

**Issue by quadronet** [tomasnorre/crawler#847]
## Bug Report

The crawler didn´t start, TYPO3 10, news crawler. 

Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAssociative()

in /var/www/vhosts/domain/typo3conf/ext/crawler/Classes/Domain/Repository/QueueRepository.php line 639

**while ($row = $statement->fetchAssociative()) {**
            $rows[] = $row['qid'];
        }

**Comment by tomasnorre** [comment]
Hi. 

Thanks for your report, but I need a little more information. 

Crawler Version? 
Composer mode?
PHP Version?

It looks like you are on a TYPO3 10 (non-composer) with Crawler 11.0.0,
If that's the case please update to 11.0.1 as there is a fix for this in there. 

https://github.com/tomasnorre/crawler/blob/main/CHANGELOG.md#fixed-1
