### ISSUE TITLE
[DOCS] exclude from crawling recursive

### ISSUE THREAD

**Issue by maddy2101** [tomasnorre/crawler#859]
### Is your feature request related to a problem? Please describe

I have a folder holding pages only for testing purposes, and those should not be found in the search.

### Describe the solution you would like

I wish for a crawler configuration to provide a page, and this page and all its children are excluded from crawling.

The positive variation of this is field 'pidsonly', but for exclusion, each PID has to be entered one by one in field exclude. This is error prone, when the test set grows, so I'd like to have the same possibility as for which pages to crawl.

**Comment by tomasnorre** [comment]
Hi. 

If I understand you correctly, this is already possible. 
You can use the `pageid+depth` syntax in the `exclude page field` for the Crawler configuration. The example below exclude page_id 6 and 3 levels/depth

![crawler_excludepages-recursive](https://user-images.githubusercontent.com/1212481/143224427-7f6ef200-dac0-4bc8-aea8-a55098e27db1.png)

**Comment by maddy2101** [comment]
O.O wow, never saw that before. You can help immediately by putting this into the field description and into the docu. Thanks a bunch!

**Comment by tomasnorre** [comment]
It's a missing doc. Thanks for pointing this out.
