### ISSUE TITLE
Access-restricted pages can't be crawled (403)

### ISSUE THREAD

**Issue by julianhofmann** [tomasnorre/crawler#882]
## Bug Report

**Current Behavior**
Crawling an access-restricted page (via "Usergroup Access Rights" - directly or via "Extend to Subpages") results in the status "Error - no info, sorry!". Looking at the details of the queue, the `result_data` contains "403 Forbidden"
![screenshot-2022 01 17-21_45_43](https://user-images.githubusercontent.com/25646388/149835489-213ece51-f867-471d-bc58-b0f9b9ac6c50.png)

**Expected behavior/output**
If "Crawl with FE user groups" is set in the configuration record, all pages for this FE-group should be crawlable.

**Environment**
- Crawler version: 11.0.2
- TYPO3 version: 11.5.5
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- PHP 8.0.0 (="8.0-latest FPM" at Mittwald)

**Comment by tomasnorre** [comment]
Thanks for reporting @julianhofmann. I'll look into this. Can you update the compose-mode information please? in the issue, think you simply overlooked it.

**Comment by julianhofmann** [comment]
Ops... Yes, composer-mode. (Deleted the brackets but none of the answers :-/ )

**Comment by tomasnorre** [comment]
@julianhofmann Can you please check for me if you're using directRequest or not. See https://docs.typo3.org/p/aoepeople/crawler/main/en-us/Configuration/ExtensionManagerConfiguration/Index.html

I bet that directRequests will work for you. But it's still a bug. But would be happy to know if it changes anything for you.

**Comment by tomasnorre** [comment]
I have just tested this. Switching away from DirectRequests makes this fail. 
I would suggest DirectRequests as a workaround, and I'll work on a fix.

**Comment by julianhofmann** [comment]
You've won :-) DirectRequests have been still inactive (as it is the default). Activating DirectRequests is working solution for me. Thank you!

**Comment by tomasnorre** [comment]
Thanks. Will consider updating the default, or at least update the documentation.
Thanks for testing and given me feedback.

**Comment by julianhofmann** [comment]
:-( DirectRequests does not work. Status got "OK", but result_data content is "Called TYPO3 from the wrong document root!".
Maybe it's the combination of crawler & helhum/typo3-secure-web, where document-root != web-dir != root-dir

I will continue to try and search - and report the results.

**Comment by tomasnorre** [comment]
Thanks. That can be a valid input. Let me know what you figure out. 
I'll look into it too somewhen, but don't have too much time atm. Planning the move :)

**Comment by tomasnorre** [comment]
Julian, does this

>:-( DirectRequests does not work. Status got "OK", but result_data content is "Called TYPO3 from the wrong document root!".

Happens for both Access-Restricted pages or all pages?

**Comment by tomasnorre** [comment]
Even though the status says ok, the result is: "Page Not found"

![direct_request_restrictedpage](https://user-images.githubusercontent.com/1212481/150475889-beaa6a43-d036-4b4d-9985-0655fcf307ea.png)

When using the login form on the page and visit the page manually, it's there and working. So the is definitive a bug here.

**Comment by tomasnorre** [comment]
@julianhofmann Can you please test if this is working for you. For me, it fixes the problem for both DirectRequest and non-DirectRequests.

https://github.com/tomasnorre/crawler/pull/886
