### ISSUE TITLE
sleep time and sleep after description wrong

### ISSUE THREAD

**Issue by SventB** [tomasnorre/crawler#959]
The descriptions are wrong, they are switched, e.g. for config option "sleepafter" it says "Amount of milliseconds which the system should use to relax between crawls".

**Comment by tomasnorre** [comment]
Would you mind make a PR with the change?

**Comment by tomasnorre** [comment]
Looks correct to me here: 

https://github.com/tomasnorre/crawler/blob/main/ext_conf_template.txt#L28
https://github.com/tomasnorre/crawler/blob/main/ext_conf_template.txt#L31

**Comment by SventB** [comment]
Sorry, I should have been more precise, it's wrong (or it was wrong) in ProcessQueueCommand.php, but was fixed in this commit:
https://github.com/tomasnorre/crawler/commit/cd482fbacca5332be3bf5b4808e03c170a06b0e4
But it's still wrong in newest version in TER.

**Comment by tomasnorre** [comment]
I'll close this issue then, as it's fixed in main. 
Will do a new release as soon as we are ready with a 12 compatible version. 

This will qualify for a bugfix release for the versions still getting those. 
Thanks for reporting
