### ISSUE TITLE
Undefined array key "log_resultLog"

### ISSUE THREAD

**Issue by Alagts** [tomasnorre/crawler#965]
## Bug Report

**Current Behavior**
When we click "Queue id" in the "Info" module in the TYPO3 backend when the function "Crawler log" is selected then the following error message appears: Core: Error handler (BE): PHP Warning: Undefined array key "log_resultLog" in .../public/typo3conf/ext/crawler/Classes/Backend/RequestForm/LogRequestForm.php line 159

**Expected behavior/output**
I expect that no warning should occur to produce proper results. I still see some entries, see picture: Log.png

**Steps to reproduce**
We add a crawler configuration that we called "crawlerconfiguration" and an indexed search configuration which we called "default". The crawlerconfiguration has two pages in [pidsonly] - Rootpage and one subpage of it (products - see Log.png). As configuration we insert "tx_indexedsearch_reindex". As exclude pages we add two pages in a comma separated list. 
We executed in the editor terminal of phpstorm the following commands:
php typo3 crawler:buildQueue 1 crawlerconfiguration --depth 1 --mode
php typo3 crawler:processQueue
We reload the list. Then we clicked on the link in the "Queue id" and the error message: Core: Error handler (BE): PHP Warning: Undefined array key "log_resultLog" in .../public/typo3conf/ext/crawler/Classes/Backend/RequestForm/LogRequestForm.php line 159 appears, see Error_Message.png and Array_content_of_clicked_item.png.

**Environment**
- Crawler version(s): v11.0.4
- TYPO3 version(s): v11.5.16
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
Line where error occurs:
if (! $this->infoModuleController->MOD_SETTINGS['log_resultLog']) {...}
Like this maybe: if (! (bool)($this->infoModuleController->MOD_SETTINGS['log_resultLog'] ?? false) {...}

**Additional context**
We use `indexed_search` v11.5.16. 

**Log.png**
<img width="1119" alt="Log" src="https://user-images.githubusercontent.com/16323871/199758146-65f5ccb7-b2f0-454f-93bc-54fcb0a08896.png">

**Error_Message.png**
<img width="1377" alt="Error_Message" src="https://user-images.githubusercontent.com/16323871/199759318-323932d5-b878-4569-a486-e64585424c61.png">

**Array_content_of_clicked_item.png**
<img width="1388" alt="Array_content_of_clicked_item" src="https://user-images.githubusercontent.com/16323871/199759517-1dd7eb42-9fd0-47d9-8872-c67c7aab699b.png">

**Comment by tomasnorre** [comment]
Closed with #966. 

Will create a new 11.0.5 release tomorrow.
